## 3. A grading assistant

Teachers in general have a lot of administrations to do and one of those things is grading. Can we create a simple grade assistant to assist a Swedish teacher in grading? This exercise focuses a lot in prompt engineering and afterwards to postprocess the output using Pydantic.

In [1]:
from google import genai
import pandas as pd
from pydantic import BaseModel,ValidationError

a) Go into this page with examples of students answers to a particular question. Copy some example texts and paste it into files with names like `student_text_1.txt`, `student_text_2.txt`.

b) Read these data into python and tell your LLM to grade them.

In [134]:
text_list = []
for i in range(1,3):
    with open (f"3_txt/student_{i}.txt", "r", encoding="utf-8") as file:
        text_list.append(file.read())
text_list

['Inför allas blickar\nEn av de större andledningarna att man är tal rädd är förmodligen att man är\nrädd för att folket som lyssnar på kommer göra narr av en. När man är ensam\npå en scen eller i klass rummet så är det väldigt jobbigt när det sitter ett flertal\nmänniskor som sitter och tittar på en. Jag känner mig inte så säker när jag står och\ngör en föreläsning eller en presentation. Känslan när man är framför människor\nsom man inte riktigt känner är ganska obehagligt, för man vill inte att dem ska\ntycka illa om en, eller tycka att man är konstig på något vis. Men jag tror att det\ngår att bli av med talrädslan, om man börjar i en mindre grupp och gör sig vann\nmed att prata med människor utan att bli rädd eller känna obehag.\nPeter Letmark skriver i Dagens Nyheter 2012-05-04 att det har att göra med\nevolutionära förklaringar, att man är rädd för ormar eller hundar kan ju vara\nen sak som sitter i ryggmärgen. Det kan bero på att man är rädd för att bli\nutstöt från gruppen. Letmark berättar även att primater organiserar sitt sociala\nliv i hierarkier. Rädslan för att prata i grupp kanske gör att man undviker\ndominanskonflikter. Det Letmark skriver låter ganska rimligt, mina åsikter är\nnästan desamma. Jag tror att det är lättare att prata om något som sitter nära ditt\nhjärta, för att då brinner du för det du pratar om och kan fortsätta väldigt enkelt\nutan att inte veta vad du ska prata om. Om det är något du inte tycker är så\nintressant men måste prata om det av jobb skäl, så blir det nog betydligt svårare.\nMen det blir garanterat lättare om du har bra själv förtroende, dom som har\nlite sämre själv förtroende blir du väldigt osäker på vad du säger och vågar inte\nargumentera om din åsikt.',
 'Inför allas blickar\nAtt ha muntliga presentationer är något som uppleves skrämmande i dagens\nsamhälle för att vi lever i ett samhälle där man oftast inte blir tvingade till att\ngöra något. Muntliga presentationer är något man, i de flesta fall brukar bli\ntvungen att göra i skolan först. Det händer när man är i den åldern då man\ntänker väldigt mycket på vad ens vänner tycker om en. Så att behöva stå framför\nde och presentera något kan kännas skrämmande för då tror man att de som\ntittar på dig dömer dig. Vilket blir något som fastar med en även när man blir\näldre. Muntliga presentationer är inte något man gör i skolan lika ofta som att\nlämna in en uppgift så man blir aldrig riktigt van med det. Att bli van med att\ntala framför andra är ett bra sätt att bota talängslan. Desto mer man pratar inför\nen grupp människor ju mer inser man att det inte är så farligt och man kommer\nsäkert komma på några knep på att kunna hantera sina nerver om man börjar att\nprata inför andra mycket mer. I artikeln ” därför blir vi skräckslagna” av Peter\nLetmark i DN, skriver Letmark om hur att prata inför andra var en gång i tiden\nen bra och viktigt egenskap att ha, men att dagens informationssamhälle har\ngjort det svårare och att tala inför en grupp.\nDet har blivit den vanligast rädslan för människor. Letmark skriver att rädslan\nför att tala inför grupper existerar i människor för att inte bli utstött från en viss\ngrupp. Att man inte vågade träda fram och ta plast för i tiden för att inte bli\nutstött i gruppen vilket hotade ens överlevnads chanser. Letmark skriver också\nom att man kan ärva rädslan om att tala inför grupper vilket vi människor i dag\nkan ha ärvt från våra förfäder, som undvek att ta plast i gruppen med rädslan\nav att bli utstöt. Konsekvenserna av detta är att samhället inte kommer att\nkunna utvecklas om människorna i vårt samhälle är för rädda för att ta plast\noch utrycka sig. Som jag skrev tidigare är det bra med att det blir en van att tala\ninför grupper. Letmark skriver i artikeln att man kan träna sig i små steg med att\ngöra det en vana. Man kan bara börja med att prata med sig själv framför spegel\noch sen öka publiken lite åt taget. Det viktigaste är att göra det en del av sitt\nvardagliga liv så att man verkligen måste prestera så är allting inte som en chock.']

In [135]:
from function import get_gemini
grades_simple = get_gemini(f"""Betygsätt dessa 2 texter.
        Texter:
        
        {text_list}""")
grades_simple

'Här är en bedömning av de två texterna:\n\n---\n\n### Övergripande Bedömning\n\nBåda texterna behandlar ämnet talrädsla utifrån egna resonemang och med stöd från Peter Letmarks artikel. Text 2 är generellt starkare vad gäller struktur, argumentation och språklig korrekthet, medan Text 1 har en mer personlig ton men lider av betydande språkliga brister.\n\n---\n\n### Text 1: "Inför allas blickar"\n\n**Styrkor:**\n*   **Personlig koppling:** Texten börjar med en tydlig personlig reflektion ("Jag känner mig inte så säker...") vilket gör ämnet relaterbart och engagerande.\n*   **Relevant källanvändning:** Författaren använder Peter Letmarks artikel för att bredda perspektivet med evolutionära och sociala förklaringar till talrädsla, vilket stärker argumentationen.\n*   **Egna insikter:** Författaren delar med sig av egna strategier för att övervinna rädslan (börja i mindre grupp, prata om något man brinner för, vikten av självförtroende).\n\n**Svagheter:**\n*   **Språkliga brister:** Detta är textens största svaghet. Det finns många stavfel ("andledningarna", "tal rädd", "klass rummet", "själv förtroende", "vann" istället för "van", "utstöt" istället för "utstött", "jobb skäl" istället för "jobbskäl") och grammatiska fel som stör läsflytet och ger ett mindre seriöst intryck.\n*   **Formuleringar:** Vissa meningar är klumpigt formulerade, exempelvis "utan att inte veta vad du ska prata om" (dubbel negation/onödig).\n*   **Struktur:** Även om den har en logisk följd (personlig känsla -> källa -> egna lösningar), kunde styckeindelningen och övergångarna vara tydligare för att förbättra läsbarheten.\n\n**Betyg (om det vore en skoluppgift):** **E / Godkänd med reservation** (Fokus på innehåll och källanvändning är okej, men de omfattande språkliga felen drar ner betyget kraftigt.)\n\n---\n\n### Text 2: "Inför allas blickar"\n\n**Styrkor:**\n*   **Klar struktur och argumentation:** Texten har en tydlig inledning, analyserar problemet (skola, vänner, brist på vana), presenterar Letmarks resonemang och avslutar med konkreta lösningar och ett vidare perspektiv (samhällsutveckling). Argumentationen är mer genomtänkt och följsam.\n*   **Bättre språkbruk:** Även om det finns enstaka fel (se nedan), är texten betydligt mer korrekt språkligt sett än den första. Meningarna är oftast välformulerade och läsflytet är gott.\n*   **Effektiv källanvändning:** Författaren refererar till Letmarks artikel med titel och sammanfattar dess huvudpunkter väl (historia, informationssamhället, ärvd rädsla, utstötning). Kopplingen mellan Letmarks slutsatser och de egna är tydlig.\n*   **Konkreta lösningar:** Texten ger praktiska råd för att övervinna talrädsla (vana, små steg, spegeln), vilket gör den mer handlingsorienterad.\n\n**Svagheter:**\n*   **Enstaka språkliga fel:** Fortfarande finns det några fel, exempelvis "uppleves" (ska vara "upplevs"), "fastar med en" (ska vara "fastnar med en"), "talängslan" (mindre vanligt, "talfobi" eller "talrädsla" är vanligare), och upprepade "ta plast" (ska vara "ta plats"). "Van" som substantiv istället för "vana".\n*   **Repetition:** Vissa formuleringar känns aningen repetitiva, men inte i en utsträckning som stör helheten.\n\n**Betyg (om det vore en skoluppgift):** **C / Godkänd** (Texten är välskriven och strukturerad med god argumentation. De återstående språkliga felen är färre men förhindrar ett högre betyg.)\n\n---\n\n### Sammanfattning och Jämförelse\n\nText 2 är den starkare av de två. Den har en mer genomtänkt struktur, bättre språklig korrekthet och en klarare argumentation som väver samman egna idéer med källmaterialet på ett effektivare sätt. Text 1 har en mer personlig och relaterbar inledning men dras ner av de många och grundläggande språkliga felen. För att förbättra Text 1 krävs en grundlig korrekturläsning och arbete med meningsbyggnad. Text 2 skulle gynnas av en noggrann sista korrekturläsning för att eliminera de sista språkliga bristerna.'


c) Prompt to get an output of fields proposed_grade, motivation and improvements.

In [138]:
prompt_grade_as_dict= f"""Betygsätt dessa 2 texter.
        proposed_grade ska enbart någon av dessa(A är högst, F är lägst samt icke-godkänt): A, B, C, D, E, F
        output ska vara enbart i detta json-format:
        {{
            "proposed_grade": "..",
            "motivation": "...",
            "improvements": "...",
            "proposed_grade": "..",
            osv...
        }}
        Texter:
        
        {text_list}
        
        """
grades_dict = get_gemini(prompt_grade_as_dict)
grades_dict

'```json\n[\n    {\n        "proposed_grade": "F",\n        "motivation": "Texten lider av omfattande språkfel (stavning, grammatik, ordföljd) som allvarligt försvårar läsningen och förståelsen. Till exempel \\"andledningarna\\" istället för \\"anledningarna\\", \\"tal rädd\\" istället för \\"talrädd\\", \\"gör sig vann\\" istället för \\"gör sig van\\", samt felaktig användning av pronomen och dubbla negationer. Den saknar också tydlig styckeindelning, vilket gör att argumentationen känns osammanhängande och svår att följa då alla tankar presenteras i ett enda långt stycke. Trots att en källa används, är integrationen av källan med de egna tankarna inte fullt utvecklad, och de sista meningarna känns något löst kopplade till resten av argumentationen. Det stora antalet fel i kombination med den bristande strukturen gör att texten inte når upp till en godkänd nivå.",\n        "improvements": "Fokusera på grundläggande stavning och grammatik; använd korrekturläsningsverktyg och be någon annan läsa igenom texten. Styckeindela texten logiskt för att separera olika tankar och argument (t.ex. introduktion, egen reflektion, källhänvisning, slutsats). Förbättra meningsbyggnaden och undvik upprepningar samt dubbla negationer. Fördjupa integrationen av källan genom att tydligare analysera hur källans information stödjer eller nyanserar de egna argumenten. Sträva efter ett mer formellt språk om det är syftet med uppgiften."\n    },\n    {\n        "proposed_grade": "B",\n        "motivation": "Texten är välstrukturerad och har en tydlig argumentation som effektivt integrerar egna reflektioner med information från den citerade källan. Den lyfter fram intressanta perspektiv på talrädsla, både från ett personligt/sociologiskt och evolutionärt perspektiv, och kopplar ihop detta med bredare samhälleliga konsekvenser för utveckling. Språket är i huvudsak klart, engagerande och adekvat för en uppgift av den här typen. Trots några mindre språkfel (t.ex. \\"uppleves\\" istället för \\"upplevs\\", \\"fastar\\" istället för \\"fastnar\\", \\"ta plast\\" istället för \\"ta plats\\", \\"en van\\" istället för \\"en vana\\") påverkas inte förståelsen nämnvärt, och textens styrkor överväger dessa brister.",\n        "improvements": "Gå igenom texten noggrant för att korrigera de få stavfel och grammatiska fel som finns. Förfina vissa formuleringar för att öka precisionen ytterligare (t.ex. \\"som uppleves skrämmande\\" till \\"som upplevs som skrämmande\\", \\"allting inte som en chock\\" till \\"det inte känns som en chock\\"). Se över prepositioner för att säkerställa att de är korrekta i varje kontext (t.ex. \\"utstött från\\" till \\"utstött ur\\"). Överväg att utveckla analysen av Letmarks argument ytterligare, eller kontrastera det med andra perspektiv, om utrymme och syfte tillåter, för att höja texten till en A-nivå."\n    }\n]\n```'

In [139]:
import json
grades_dict = grades_dict.strip("`json")
data = json.loads(grades_dict) 
data

[{'proposed_grade': 'F',
  'motivation': 'Texten lider av omfattande språkfel (stavning, grammatik, ordföljd) som allvarligt försvårar läsningen och förståelsen. Till exempel "andledningarna" istället för "anledningarna", "tal rädd" istället för "talrädd", "gör sig vann" istället för "gör sig van", samt felaktig användning av pronomen och dubbla negationer. Den saknar också tydlig styckeindelning, vilket gör att argumentationen känns osammanhängande och svår att följa då alla tankar presenteras i ett enda långt stycke. Trots att en källa används, är integrationen av källan med de egna tankarna inte fullt utvecklad, och de sista meningarna känns något löst kopplade till resten av argumentationen. Det stora antalet fel i kombination med den bristande strukturen gör att texten inte når upp till en godkänd nivå.',
  'improvements': 'Fokusera på grundläggande stavning och grammatik; använd korrekturläsningsverktyg och be någon annan läsa igenom texten. Styckeindela texten logiskt för att separera olika tankar och argument (t.ex. introduktion, egen reflektion, källhänvisning, slutsats). Förbättra meningsbyggnaden och undvik upprepningar samt dubbla negationer. Fördjupa integrationen av källan genom att tydligare analysera hur källans information stödjer eller nyanserar de egna argumenten. Sträva efter ett mer formellt språk om det är syftet med uppgiften.'},
 {'proposed_grade': 'B',
  'motivation': 'Texten är välstrukturerad och har en tydlig argumentation som effektivt integrerar egna reflektioner med information från den citerade källan. Den lyfter fram intressanta perspektiv på talrädsla, både från ett personligt/sociologiskt och evolutionärt perspektiv, och kopplar ihop detta med bredare samhälleliga konsekvenser för utveckling. Språket är i huvudsak klart, engagerande och adekvat för en uppgift av den här typen. Trots några mindre språkfel (t.ex. "uppleves" istället för "upplevs", "fastar" istället för "fastnar", "ta plast" istället för "ta plats", "en van" istället för "en vana") påverkas inte förståelsen nämnvärt, och textens styrkor överväger dessa brister.',
  'improvements': 'Gå igenom texten noggrant för att korrigera de få stavfel och grammatiska fel som finns. Förfina vissa formuleringar för att öka precisionen ytterligare (t.ex. "som uppleves skrämmande" till "som upplevs som skrämmande", "allting inte som en chock" till "det inte känns som en chock"). Se över prepositioner för att säkerställa att de är korrekta i varje kontext (t.ex. "utstött från" till "utstött ur"). Överväg att utveckla analysen av Letmarks argument ytterligare, eller kontrastera det med andra perspektiv, om utrymme och syfte tillåter, för att höja texten till en A-nivå.'}]


d) Now validate this with pydantic model

In [140]:
from typing import Literal
from pydantic import BaseModel, ValidationError
class Grades(BaseModel): 
    proposed_grade: Literal["A", "B", "C","D","E","F"]
    motivation: str
    improvements: str
    
validated_grades = []
try:
    for d in data: 
        validated_grades.append(Grades.model_validate(d))
except ValidationError as err:
    print(err) 
len(validated_grades), validated_grades

(2,
 [Grades(proposed_grade='F', motivation='Texten lider av omfattande språkfel (stavning, grammatik, ordföljd) som allvarligt försvårar läsningen och förståelsen. Till exempel "andledningarna" istället för "anledningarna", "tal rädd" istället för "talrädd", "gör sig vann" istället för "gör sig van", samt felaktig användning av pronomen och dubbla negationer. Den saknar också tydlig styckeindelning, vilket gör att argumentationen känns osammanhängande och svår att följa då alla tankar presenteras i ett enda långt stycke. Trots att en källa används, är integrationen av källan med de egna tankarna inte fullt utvecklad, och de sista meningarna känns något löst kopplade till resten av argumentationen. Det stora antalet fel i kombination med den bristande strukturen gör att texten inte når upp till en godkänd nivå.', improvements='Fokusera på grundläggande stavning och grammatik; använd korrekturläsningsverktyg och be någon annan läsa igenom texten. Styckeindela texten logiskt för att separera olika tankar och argument (t.ex. introduktion, egen reflektion, källhänvisning, slutsats). Förbättra meningsbyggnaden och undvik upprepningar samt dubbla negationer. Fördjupa integrationen av källan genom att tydligare analysera hur källans information stödjer eller nyanserar de egna argumenten. Sträva efter ett mer formellt språk om det är syftet med uppgiften.'),
  Grades(proposed_grade='B', motivation='Texten är välstrukturerad och har en tydlig argumentation som effektivt integrerar egna reflektioner med information från den citerade källan. Den lyfter fram intressanta perspektiv på talrädsla, både från ett personligt/sociologiskt och evolutionärt perspektiv, och kopplar ihop detta med bredare samhälleliga konsekvenser för utveckling. Språket är i huvudsak klart, engagerande och adekvat för en uppgift av den här typen. Trots några mindre språkfel (t.ex. "uppleves" istället för "upplevs", "fastar" istället för "fastnar", "ta plast" istället för "ta plats", "en van" istället för "en vana") påverkas inte förståelsen nämnvärt, och textens styrkor överväger dessa brister.', improvements='Gå igenom texten noggrant för att korrigera de få stavfel och grammatiska fel som finns. Förfina vissa formuleringar för att öka precisionen ytterligare (t.ex. "som uppleves skrämmande" till "som upplevs som skrämmande", "allting inte som en chock" till "det inte känns som en chock"). Se över prepositioner för att säkerställa att de är korrekta i varje kontext (t.ex. "utstött från" till "utstött ur"). Överväg att utveckla analysen av Letmarks argument ytterligare, eller kontrastera det med andra perspektiv, om utrymme och syfte tillåter, för att höja texten till en A-nivå.')])


e) Output a folder with the following txt files: proposed_grade.txt, motivation.txt and improvements.txt

In [143]:
import pandas as pd 
grade_dict = [g.model_dump() for g in validated_grades]

df_grades = pd.DataFrame(grade_dict)
df_grades

df_grades["proposed_grade"].to_csv("3_txt/proposed_grade.txt")
df_grades["motivation"].to_csv("3_txt/motivation.txt")
df_grades["improvements"].to_csv("3_txt/improvements.txt")


f) Go [into skolverket for Svenska 1](https://www.skolverket.se/undervisning/gymnasieskolan/program-och-amnen-i-gymnasieskolan/hitta-program-amnen-och-kurser-i-gymnasieskolan-gy11/amne?url=907561864%2Fsyllabuscw%2Fjsp%2Fsubject.htm%3FsubjectCode%3DSVE%26version%3D8%26tos%3Dgy&sv.url=12.5dfee44715d35a5cdfa92a3) and copy "Betygskriterier" for "Svenska 1". These are the criterias for the different grades. Paste this into a file called `criterias.txt`.

In [144]:
with open("3_txt/criterias.txt", "r", encoding="utf-8") as file: 
    criterias = file.read()
criterias[:200]

'Betygskriterier\nBetyget E\n\nEleven kan, i förberedda samtal och diskussioner, muntligt förmedla egna tankar och åsikter samt genomföra muntlig framställning inför en grupp. Detta gör eleven med viss sä'


g) Now repeat b)-e) but with the criterias in your prompt as well. Can you see any differences in the outputs?

- b) Read these data into python and tell your LLM to grade them.

- c) Prompt to get an output of fields proposed_grade, motivation and improvements.

In [145]:
from function import get_gemini
prompt_grade_as_dict= f"""Betygsätt dessa 2 texter.
        proposed_grade enbart någon av dessa(A är högst, F är inte godkänt): A, B, C, D, E, F och utgå utifrån dessa betygskriterier:
        {criterias}
        output ska vara enbart i detta json-format:
        {{
            "proposed_grade": "..",
            "motivation": "...",
            "improvements": "...",
            "proposed_grade": "..",
            osv...
        }}
        Texter:
        
        {text_list}
        
        """
output = get_gemini(prompt_grade_as_dict)
output

'```json\n[\n    {\n        "proposed_grade": "F",\n        "motivation": "Texten lider av frekventa och grundläggande brister i språkriktigheten, inklusive stavfel (t.ex. \\"andledningarna\\", \\"vann\\"), felaktiga sammansättningar (t.ex. \\"klass rummet\\", \\"själv förtroende\\", \\"jobb skäl\\"), grammatiska fel (t.ex. \\"utstöt från\\", dubbel negation) och bristande meningsbyggnad/interpunktion. Dessa brister försvårar läsbarheten och tydligheten avsevärt, vilket gör att texten inte \\"i huvudsak följer skriftspråkets normer för språkriktighet\\" som krävs för ett E. Dispositionen är inte tydligt urskiljbar, och elevens reflektion över källan är ytlig och begränsas till att enbart instämma.",\n        "improvements": "1. **Språkriktighet:** Fokusera på grundläggande stavning, korrekta sammansättningar och grammatiska regler. Läs igenom texten noga för att identifiera och korrigera fel. Använd verktyg för stavnings- och grammatikkontroll. 2. **Meningsbyggnad och interpunktion:** Öva på att variera meningsbyggnaden och att använda kommatecken och punkt korrekt för att skapa tydligare och mer flytande meningar. 3. **Struktur och disposition:** Arbeta med att organisera texten i tydliga stycken med en klar inledning, argumentation och avslutning. Varje stycke bör ha ett avgränsat tema. 4. **Källhantering och analys:** Utveckla den egna reflektionen över källan. Istället för att enbart instämma, försök att analysera, jämföra eller fördjupa Letmarks argument med egna exempel, motargument eller nya perspektiv."\n    },\n    {\n        "proposed_grade": "E",\n        "motivation": "Texten är sammanhängande och begriplig, och dispositionen är tydligt urskiljbar med en logisk uppbyggnad från personliga observationer till teoretiska förklaringar och lösningar. Eleven integrerar den refererade källan väl genom att sammanfatta centrala delar och relatera dem till samhälleliga konsekvenser och egna tankar. Detta visar förmåga att \\"läsa, reflektera över och göra sammanfattningar av texter\\" samt att skriva egna texter som \\"lyfter fram huvudtanken i det lästa\\". Dock innehåller texten fortfarande ett märkbart antal fel i språkriktighet (t.ex. stavfel som \\"uppleves\\", \\"fastar\\", \\"plast\\", \\"utrycka\\"; grammatiska fel med prepositionsval och meningsbyggnad). Dessa brister i språkriktigheten hindrar texten från att uppnå en högre bedömning, då den inte konsekvent uppfyller kravet att \\"i huvudsak följa skriftspråkets normer för språkriktighet\\" för ett C, och språket är inte genomgående \\"varierat och delvis välformulerat\\".",\n        "improvements": "1. **Språkriktighet:** En grundlig korrekturläsning är avgörande för att åtgärda de återkommande stavfelen (t.ex. \\"plats\\", \\"uttrycka\\"), grammatiska felen (t.ex. passivform, prepositionsval) och felaktiga sammansättningar. Sträva efter att följa skriftspråkets normer mer konsekvent. 2. **Meningsbyggnad och formulering:** Arbeta med att förfina meningsstrukturen för att undvika långa, ibland något krångliga meningar. Sträva efter mer precisa, nyanserade och varierade formuleringar för att höja textens språkliga kvalitet. 3. **Källhantering:** Även om källan används bra, finns det utrymme att fördjupa den kritiska granskningen eller presentera fler perspektiv på Letmarks argument, snarare än att enbart återge och bygga vidare på dem."\n    }\n]\n```'

In [146]:
print(output)

```json
[
    {
        "proposed_grade": "F",
        "motivation": "Texten lider av frekventa och grundläggande brister i språkriktigheten, inklusive stavfel (t.ex. \"andledningarna\", \"vann\"), felaktiga sammansättningar (t.ex. \"klass rummet\", \"själv förtroende\", \"jobb skäl\"), grammatiska fel (t.ex. \"utstöt från\", dubbel negation) och bristande meningsbyggnad/interpunktion. Dessa brister försvårar läsbarheten och tydligheten avsevärt, vilket gör att texten inte \"i huvudsak följer skriftspråkets normer för språkriktighet\" som krävs för ett E. Dispositionen är inte tydligt urskiljbar, och elevens reflektion över källan är ytlig och begränsas till att enbart instämma.",
        "improvements": "1. **Språkriktighet:** Fokusera på grundläggande stavning, korrekta sammansättningar och grammatiska regler. Läs igenom texten noga för att identifiera och korrigera fel. Använd verktyg för stavnings- och grammatikkontroll. 2. **Meningsbyggnad och interpunktion:** Öva på att variera meningsbyggnaden och att använda kommatecken och punkt korrekt för att skapa tydligare och mer flytande meningar. 3. **Struktur och disposition:** Arbeta med att organisera texten i tydliga stycken med en klar inledning, argumentation och avslutning. Varje stycke bör ha ett avgränsat tema. 4. **Källhantering och analys:** Utveckla den egna reflektionen över källan. Istället för att enbart instämma, försök att analysera, jämföra eller fördjupa Letmarks argument med egna exempel, motargument eller nya perspektiv."
    },
    {
        "proposed_grade": "E",
        "motivation": "Texten är sammanhängande och begriplig, och dispositionen är tydligt urskiljbar med en logisk uppbyggnad från personliga observationer till teoretiska förklaringar och lösningar. Eleven integrerar den refererade källan väl genom att sammanfatta centrala delar och relatera dem till samhälleliga konsekvenser och egna tankar. Detta visar förmåga att \"läsa, reflektera över och göra sammanfattningar av texter\" samt att skriva egna texter som \"lyfter fram huvudtanken i det lästa\". Dock innehåller texten fortfarande ett märkbart antal fel i språkriktighet (t.ex. stavfel som \"uppleves\", \"fastar\", \"plast\", \"utrycka\"; grammatiska fel med prepositionsval och meningsbyggnad). Dessa brister i språkriktigheten hindrar texten från att uppnå en högre bedömning, då den inte konsekvent uppfyller kravet att \"i huvudsak följa skriftspråkets normer för språkriktighet\" för ett C, och språket är inte genomgående \"varierat och delvis välformulerat\".",
        "improvements": "1. **Språkriktighet:** En grundlig korrekturläsning är avgörande för att åtgärda de återkommande stavfelen (t.ex. \"plats\", \"uttrycka\"), grammatiska felen (t.ex. passivform, prepositionsval) och felaktiga sammansättningar. Sträva efter att följa skriftspråkets normer mer konsekvent. 2. **Meningsbyggnad och formulering:** Arbeta med att förfina meningsstrukturen för att undvika långa, ibland något krångliga meningar. Sträva efter mer precisa, nyanserade och varierade formuleringar för att höja textens språkliga kvalitet. 3. **Källhantering:** Även om källan används bra, finns det utrymme att fördjupa den kritiska granskningen eller presentera fler perspektiv på Letmarks argument, snarare än att enbart återge och bygga vidare på dem."
    }
]
```

In [147]:
cleaned = output.strip("`json")
# output = output.strip("")
data = json.loads(cleaned)
print(data)
# print(output)

[{'proposed_grade': 'F', 'motivation': 'Texten lider av frekventa och grundläggande brister i språkriktigheten, inklusive stavfel (t.ex. "andledningarna", "vann"), felaktiga sammansättningar (t.ex. "klass rummet", "själv förtroende", "jobb skäl"), grammatiska fel (t.ex. "utstöt från", dubbel negation) och bristande meningsbyggnad/interpunktion. Dessa brister försvårar läsbarheten och tydligheten avsevärt, vilket gör att texten inte "i huvudsak följer skriftspråkets normer för språkriktighet" som krävs för ett E. Dispositionen är inte tydligt urskiljbar, och elevens reflektion över källan är ytlig och begränsas till att enbart instämma.', 'improvements': '1. **Språkriktighet:** Fokusera på grundläggande stavning, korrekta sammansättningar och grammatiska regler. Läs igenom texten noga för att identifiera och korrigera fel. Använd verktyg för stavnings- och grammatikkontroll. 2. **Meningsbyggnad och interpunktion:** Öva på att variera meningsbyggnaden och att använda kommatecken och punkt korrekt för att skapa tydligare och mer flytande meningar. 3. **Struktur och disposition:** Arbeta med att organisera texten i tydliga stycken med en klar inledning, argumentation och avslutning. Varje stycke bör ha ett avgränsat tema. 4. **Källhantering och analys:** Utveckla den egna reflektionen över källan. Istället för att enbart instämma, försök att analysera, jämföra eller fördjupa Letmarks argument med egna exempel, motargument eller nya perspektiv.'}, {'proposed_grade': 'E', 'motivation': 'Texten är sammanhängande och begriplig, och dispositionen är tydligt urskiljbar med en logisk uppbyggnad från personliga observationer till teoretiska förklaringar och lösningar. Eleven integrerar den refererade källan väl genom att sammanfatta centrala delar och relatera dem till samhälleliga konsekvenser och egna tankar. Detta visar förmåga att "läsa, reflektera över och göra sammanfattningar av texter" samt att skriva egna texter som "lyfter fram huvudtanken i det lästa". Dock innehåller texten fortfarande ett märkbart antal fel i språkriktighet (t.ex. stavfel som "uppleves", "fastar", "plast", "utrycka"; grammatiska fel med prepositionsval och meningsbyggnad). Dessa brister i språkriktigheten hindrar texten från att uppnå en högre bedömning, då den inte konsekvent uppfyller kravet att "i huvudsak följa skriftspråkets normer för språkriktighet" för ett C, och språket är inte genomgående "varierat och delvis välformulerat".', 'improvements': '1. **Språkriktighet:** En grundlig korrekturläsning är avgörande för att åtgärda de återkommande stavfelen (t.ex. "plats", "uttrycka"), grammatiska felen (t.ex. passivform, prepositionsval) och felaktiga sammansättningar. Sträva efter att följa skriftspråkets normer mer konsekvent. 2. **Meningsbyggnad och formulering:** Arbeta med att förfina meningsstrukturen för att undvika långa, ibland något krångliga meningar. Sträva efter mer precisa, nyanserade och varierade formuleringar för att höja textens språkliga kvalitet. 3. **Källhantering:** Även om källan används bra, finns det utrymme att fördjupa den kritiska granskningen eller presentera fler perspektiv på Letmarks argument, snarare än att enbart återge och bygga vidare på dem.'}]

- d) Now validate this with pydantic model

In [149]:
from pydantic import BaseModel, ValidationError
from typing import Literal
class GradesCriterias(BaseModel): 
    proposed_grade: Literal["A", "B", "C", "D", "E", "F"]
    motivation: str 
    improvements: str

valid_grades_crits = []
for d in data: 
    try:
        valid_grades_crits.append(GradesCriterias.model_validate(d))
    except ValidationError as err: 
        print(err)
valid_grades_crits

[GradesCriterias(proposed_grade='F', motivation='Texten lider av frekventa och grundläggande brister i språkriktigheten, inklusive stavfel (t.ex. "andledningarna", "vann"), felaktiga sammansättningar (t.ex. "klass rummet", "själv förtroende", "jobb skäl"), grammatiska fel (t.ex. "utstöt från", dubbel negation) och bristande meningsbyggnad/interpunktion. Dessa brister försvårar läsbarheten och tydligheten avsevärt, vilket gör att texten inte "i huvudsak följer skriftspråkets normer för språkriktighet" som krävs för ett E. Dispositionen är inte tydligt urskiljbar, och elevens reflektion över källan är ytlig och begränsas till att enbart instämma.', improvements='1. **Språkriktighet:** Fokusera på grundläggande stavning, korrekta sammansättningar och grammatiska regler. Läs igenom texten noga för att identifiera och korrigera fel. Använd verktyg för stavnings- och grammatikkontroll. 2. **Meningsbyggnad och interpunktion:** Öva på att variera meningsbyggnaden och att använda kommatecken och punkt korrekt för att skapa tydligare och mer flytande meningar. 3. **Struktur och disposition:** Arbeta med att organisera texten i tydliga stycken med en klar inledning, argumentation och avslutning. Varje stycke bör ha ett avgränsat tema. 4. **Källhantering och analys:** Utveckla den egna reflektionen över källan. Istället för att enbart instämma, försök att analysera, jämföra eller fördjupa Letmarks argument med egna exempel, motargument eller nya perspektiv.'),
 GradesCriterias(proposed_grade='E', motivation='Texten är sammanhängande och begriplig, och dispositionen är tydligt urskiljbar med en logisk uppbyggnad från personliga observationer till teoretiska förklaringar och lösningar. Eleven integrerar den refererade källan väl genom att sammanfatta centrala delar och relatera dem till samhälleliga konsekvenser och egna tankar. Detta visar förmåga att "läsa, reflektera över och göra sammanfattningar av texter" samt att skriva egna texter som "lyfter fram huvudtanken i det lästa". Dock innehåller texten fortfarande ett märkbart antal fel i språkriktighet (t.ex. stavfel som "uppleves", "fastar", "plast", "utrycka"; grammatiska fel med prepositionsval och meningsbyggnad). Dessa brister i språkriktigheten hindrar texten från att uppnå en högre bedömning, då den inte konsekvent uppfyller kravet att "i huvudsak följa skriftspråkets normer för språkriktighet" för ett C, och språket är inte genomgående "varierat och delvis välformulerat".', improvements='1. **Språkriktighet:** En grundlig korrekturläsning är avgörande för att åtgärda de återkommande stavfelen (t.ex. "plats", "uttrycka"), grammatiska felen (t.ex. passivform, prepositionsval) och felaktiga sammansättningar. Sträva efter att följa skriftspråkets normer mer konsekvent. 2. **Meningsbyggnad och formulering:** Arbeta med att förfina meningsstrukturen för att undvika långa, ibland något krångliga meningar. Sträva efter mer precisa, nyanserade och varierade formuleringar för att höja textens språkliga kvalitet. 3. **Källhantering:** Även om källan används bra, finns det utrymme att fördjupa den kritiska granskningen eller presentera fler perspektiv på Letmarks argument, snarare än att enbart återge och bygga vidare på dem.')]

In [150]:
grades_crit_dict = [grade.model_dump() for grade in valid_grades_crits]
df_grades_crit = pd.DataFrame(grades_crit_dict)
df_grades_crit

,proposed_grade,motivation,improvements
0,F,Texten lider av frekventa och grundläggande br...,1. **Språkriktighet:** Fokusera på grundläggan...
1,E,"Texten är sammanhängande och begriplig, och di...",1. **Språkriktighet:** En grundlig korrekturlä...

- e) Output a folder with the following txt files: proposed_grade.txt, motivation.txt and improvements.txt

In [151]:
df_grades_crit["improvements"].to_csv("3_txt/improvements_2.txt")
df_grades_crit["motivation"].to_csv("3_txt/motivation_2.txt")
df_grades_crit["proposed_grade"].to_csv("3_txt/proposed_grade_2.txt")

### Difference in grades from gemini, with criteras vs without criterias

In [153]:
# df_summary = 
# df_summary = df_grades["proposed_grade"] 
# df_summary = df_summary.rename("proposed_grade_without")
# # df_summary = df_grades_crit["proposed_grade"]
# pd.DataFrame(df_summary)
dict_summary = {
    "proposed_grade_without_criterias": df_grades["proposed_grade"],
    "proposed_grade_with_criterias": df_grades_crit["proposed_grade"],
    # "facit_from_chatgpt": ["E", "E","C","C","A"] 
    
}
df_summary = pd.DataFrame(dict_summary)
df_summary

  proposed_grade_without_criterias proposed_grade_with_criterias
0                                F                             F
1                                B                             E

h) Can you improve the output quality by providing few shot examples?
- done